[package]
license = ["Apache-2.0"]
keywords = ["IT Operations/Authentication", "Cost/Freemium"]
org = "ballerinax"
name = "trigger.asgardeo"
repository = "https://github.com/ballerina-platform/asyncapi-triggers"
version = "0.0.6"
distribution = "2201.0.1"
icon = "docs/icon.png"
authors = ["Ballerina"]

[build-options]
observabilityIncluded = true
