[package]
license = ["Apache-2.0"]
keywords = ["Communication/Email", "Cost/Freemium", "Trigger"]
org = "ballerinax"
name = "trigger.gmail"
repository = "https://github.com/ballerina-platform/asyncapi-triggers"
version = "0.0.1"
distribution = "slbeta6"
icon = "docs/icon.png"
authors = ["Ballerina"]

[build-options]
observabilityIncluded = true
