[package]
org = "ballerinax"
name = "trigger.asb"
version = "1.1.2"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["IT Operations/Message Brokers", "Cost/Paid", "Vendor/Microsoft"]
icon = "docs/icon.png"
repository = "https://github.com/ballerina-platform/asyncapi-triggers"
distribution = "2202.4.1"

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
path = "../../native/asb/build/libs/asb-1.1.0.jar"
groupId = "org.ballerinax"
artifactId = "asb"
module = "asb" 
version = "1.1.0"

