[package]
license = ["Apache-2.0"]
keywords = ["Cost/Freemium", "Trigger"]
org = "ballerinax"
name = "trigger.google.calendar"
repository = "https://github.com/ballerina-platform/asyncapi-triggers"
version = "0.5.4"
distribution = "slbeta6"
icon = "docs/icon.png"
authors = ["Ballerina"]

[build-options]
observabilityIncluded = true
